export const MENU_ITEMS = [
    {
        id: 1,
        title: "Espresso",
        description: "Strong, concentrated coffee.",
        title_ar: "إسبريسو",
        description_ar: "قهوة قوية ومركزة.",
    },
    {
        id: 2,
        title: "Americano",
        description: "Espresso diluted with hot water.",
        title_ar: "أمريكانو",
        description_ar: "إسبريسو مخفف بالماء الساخن.",
    },
    {
        id: 3,
        title: "Latte",
        description: "Espresso with steamed milk and foam.",
        title_ar: "لاتيه",
        description_ar: "إسبريسو مع حليب مبخر ورغوة.",
    },
    {
        id: 4,
        title: "Cappuccino",
        description: "Equal parts espresso, milk, and foam.",
        title_ar: "كابتشينو",
        description_ar: "أجزاء متساوية من الإسبريسو والحليب والرغوة.",
    },
    {
        id: 5,
        title: "Macchiato",
        description: "Espresso with a dollop of foam.",
        title_ar: "ماكياتو",
        description_ar: "إسبريسو مع ملعقة من الرغوة.",
    },
    {
        id: 6,
        title: "Mocha",
        description: "Latte with chocolate flavor.",
        title_ar: "موكا",
        description_ar: "لاتيه بنكهة الشوكولاتة.",
    },
    {
        id: 7,
        title: "Flat White",
        description: "Espresso with velvety steamed milk.",
        title_ar: "فلات وايت",
        description_ar: "إسبريسو مع حليب مبخر ناعم.",
    },
    {
        id: 8,
        title: "Cortado",
        description: "Equal parts espresso and milk.",
        title_ar: "كورتادو",
        description_ar: "أجزاء متساوية من الإسبريسو والحليب.",
    },
    {
        id: 9,
        title: "Cold Brew",
        description: "Cold water brewed coffee.",
        title_ar: "كولد برو",
        description_ar: "قهوة تخمر بالماء البارد.",
    },
    {
        id: 10,
        title: "Affogato",
        description: "Espresso over ice cream.",
        title_ar: "أفوجاتو",
        description_ar: "إسبريسو على الآيس كريم.",
    },
];
